apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    memory: "256"
    path: /
  generation: 1
  labels:
    app: test-ui
  name: test-ui
  namespace: bc-op 
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-ui
        version: v1.0
        workload: test-ui
    spec:
      nodeSelector:
        noderole: bc-op
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test-ui
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: registry.paas/bcop/test-ui:$version
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /test-ui/healthcheck
            port: 5009
          initialDelaySeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /test-ui/healthcheck
            port: 5009
          initialDelaySeconds: 15
          failureThreshold: 3
        name: test-ui
        resources:
          limits:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: test-ui
  name: test-ui
  namespace: bc-op
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 50800
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
  - name: http
    port: 5009
    protocol: TCP
    targetPort: 5009
  selector:
    app: test-ui

